from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import sys


def wine_assigner(wine,red_list,white_list,sparkling_list):
    if wine in red_list:
        return "Red"
    elif wine in white_list:
        return "White"
    elif wine in sparkling_list:
        return "Sparkling"
    else:
        return "Other/Unknown"


def continent_checker(country):
    na = {"US", "Canada", "Mexico"}
    sa = {"Brazil", "Chile", "Argentina", "Peru", "Uruguay"}
    eur = {
        "Italy",
        "Portugal",
        "Spain",
        "France",
        "Germany",
        "Austria",
        "Hungary",
        "Moldova",
        "Serbia",
        "Greece",
        "Romania",
        "Turkey",
        "Czech Republic",
        "Slovenia",
        "Luxembourg",
        "Croatia",
        "England",
        "Bulgaria",
        "Cyprus",
        "Switzerland",
        "Ukraine",
        "Slovakia",
        "Macedonia",
        "Bosnia and Herzegovina",
    }
    afr = {"South Africa", "Egypt", "Morocco"}
    asia = {"China", "Israel", "Lebanon", "India", "Armenia", "Georgia"}
    aus = {"Australia", "New Zealand"}

    if country in na:
        return "North America"
    elif country in sa:
        return "South America"
    elif country in eur:
        return "Europe"
    elif country in afr:
        return "Africa"
    elif country in asia:
        return "Asia"
    elif country in aus:
        return "Australia"
    else:
        return "NA"


reds = {
    "Alfrocheiro",
    "Austrian Red Blend",
    "Bordeaux-style Red Blend",
    "Portuguese Red",
    "Provence red blend",
    "Aglianico",
    "Agiorgitiko",
    "Alicante Bouschet",
    "Baco Noir",
    "Baga",
    "Barbera",
    "Black Muscat",
    "Blaufränkisch",
    "Bobal",
    "Bonarda",
    "Brachetto",
    "Cabernet",
    "Cabernet Blend",
    "Cabernet Franc",
    "Cabernet Franc-Cabernet Sauvignon",
    "Cabernet Franc-Merlot",
    "Cabernet Merlot",
    "Cabernet Sauvignon",
    "Tinta Fina",
    "Tinta Roriz",
    "Tinta de Toro",
    "Tinto Fino",
    "Tinto del Pais",
    "Cabernet Sauvignon-Cabernet Franc",
    "Cabernet Sauvignon-Carmenère",
    "Gamay",
    "Cabernet Sauvignon-Malbec",
    "Gaglioppo",
    "Cabernet Sauvignon-Merlot",
    "Gamay Noir",
    "Garnacha-Syrah",
    "Cabernet Sauvignon-Shiraz",
    "Dolcetto",
    "Garnacha",
    "Cabernet Sauvignon-Syrah",
    "Claret",
    "Corvina",
    "Lemberger",
    "Corvina, Rondinella, Molinara",
    "Counoise",
    "Graciano",
    "Cabernet Sauvignon-Tempranillo",
    "Cinsault",
    "Grenache",
    "Grenache-Carignan",
    "Kalecik Karasi",
    "Lambrusco",
    "Lambrusco Grasparossa",
    "Lambrusco di Sorbara",
    "Raboso",
    "Grenache-Syrah",
    "Lagrein",
    "Malbec",
    "Mencía",
    "Nero di Troia",
    "Malbec-Cabernet Franc",
    "Meritage",
    "Merlot",
    "Merlot-Cabernet",
    "Merlot-Cabernet Franc",
    "Merlot-Cabernet Sauvignon",
    "Norton",
    "Malbec-Cabernet Sauvignon",
    "Monastrell",
    "Mondeuse",
    "Petite Verdot",
    "Malbec-Merlot",
    "Monastrell-Syrah",
    "Montepulciano",
    "Piedirosso",
    "Malbec-Syrah",
    "Moscatel",
    "Mourvèdre",
    "Negroamaro",
    "Petit Verdot",
    "Malbec-Tannat",
    "Nebbiolo",
    "Negrette",
    "Nerello Mascalese",
    "Pinot Nero",
    "Pinot Noir",
    "Pinotage",
    "Plavac Mali",
    "Portuguese Rosé",
    "Red Blend",
    "Syrah",
    "Syrah-Cabernet",
    "Syrah-Cabernet Sauvignon",
    "Syrah-Grenache",
    "Syrah-Mourvèdre",
    "Syrah-Petite Sirah",
    "Pinot Noir-Gamay",
    "Port",
    "Prieto Picudo",
    "Primitivo",
    "Rhône-style Red Blend",
    "Cabernet-Syrah",
    "Cannonau",
    "Carignan",
    "G-S-M",
    "Nero d'Avola",
    "Refosco",
    "Rosado",
    "Rosato",
    "Ruché",
    "Sagrantino",
    "Sangiovese",
    "Saperavi",
    "Schiava",
    "Shiraz",
    "Shiraz-Cabernet Sauvignon",
    "Shiraz-Grenache",
    "Shiraz-Viognier",
    "Spätburgunder",
    "Sangiovese Grosso",
    "St. Laurent",
    "Syrah-Viognier",
    "Tannat",
    "Tannat-Cabernet",
    "Tannat-Cabernet Franc",
    "Tempranillo",
    "Tempranillo Blend",
    "Tempranillo-Cabernet Sauvignon",
    "Tempranillo-Garnacha",
    "Tannat-Merlot",
    "Rosé",
    "Teroldego",
    "Uva di Troia",
    "Zinfandel",
    "Carignane",
    "Chambourcin",
    "Charbono",
    "Dornfelder",
    "Petite Sirah",
    "Xinomavro",
    "Touriga Nacional",
    "Trincadeira",
    "Touriga Nacional Blend",
    "Touriga Nacional-Cabernet Sauvignon",
    "Carignano",
    "Carmenère",
    "Castelão",
    "Frappato",
    "Prugnolo Gentile",
    "Zweigelt",
}
whites = {
    "Albana",
    "Albariño",
    "Alsace white blend",
    "Austrian white blend",
    "Bordeaux-style White Blend",
    "Chenin Blanc",
    "Aligoté",
    "Alvarinho",
    "Antão Vaz",
    "Arinto",
    "Arneis",
    "Assyrtico",
    "Assyrtiko",
    "Auxerrois",
    "Carricante",
    "Catarratto",
    "Chardonnay",
    "Chardonnay-Viognier",
    "Coda di Volpe",
    "Colombard",
    "Cortese",
    "Encruzado",
    "Falanghina",
    "Fernão Pires",
    "Fiano",
    "Friulano",
    "Fumé Blanc",
    "Furmint",
    "Garganega",
    "Gelber Muskateller",
    "Gewürztraminer",
    "Godello",
    "Grauburgunder",
    "Grechetto",
    "Greco",
    "Grillo",
    "Gros Manseng",
    "Gros and Petit Manseng",
    "Grüner Veltliner",
    "Hondarrabi Zuri",
    "Insolia",
    "Inzolia",
    "Jacquère",
    "Kerner",
    "Loureiro",
    "Macabeo",
    "Malagousia",
    "Malvasia",
    "Malvasia Bianca",
    "Marsanne",
    "Marsanne-Roussanne",
    "Melon",
    "Moscato",
    "Moscato Giallo",
    "Muscat",
    "Muscat Blanc",
    "Muscat Canelli",
    "Muskat Ottonel",
    "Müller-Thurgau",
    "Neuburger",
    "Orange Muscat",
    "Palomino",
    "Pansa Blanca",
    "Passerina",
    "Pecorino",
    "Pedro Ximénez",
    "Petit Manseng",
    "Picolit",
    "Picpoul",
    "Pinot Auxerrois",
    "Pinot Bianco",
    "Pinot Grigio",
    "Pinot Gris",
    "Pinot Meunier",
    "Rhône-style White Blend",
    "Ribolla Gialla",
    "Riesling",
    "Rkatsiteli",
    "Rotgipfler",
    "Roussanne",
    "Roussanne-Viognier",
    "Sauvignon",
    "Sauvignon Gris",
    "Savagnin",
    "Scheurebe",
    "Seyval Blanc",
    "Sherry",
    "Silvaner",
    "Siria",
    "Sylvaner",
    "Sémillon",
    "Tocai Friulano",
    "Tokaji",
    "Torrontés",
    "Traminer",
    "Trebbiano",
    "Turbiana",
    "Verdejo",
    "Verdejo-Viura",
    "Verdelho",
    "Verdicchio",
    "Vermentino",
    "Vernaccia",
    "Vidal Blanc",
    "Vidal",
    "Vignoles",
    "Viognier",
    "Welschriesling",
    "Xarel-lo",
    "Viognier-Chardonnay",
    "White Riesling",
    "Zibibbo",
    "Zierfandler",
    "Viura",
    "Viura-Chardonnay",
    "Weissburgunder",
    "Chenin Blanc-Chardonnay",
    "Chenin Blanc-Viognier",
    "Colombard-Sauvignon Blanc",
    "Garnacha Blanca",
    "Grenache Blanc",
    "Portuguese White",
    "Provence white blend",
    "Sauvignon Blanc",
    "Moschofilero",
    "Sauvignon Blanc-Semillon",
    "Semillon-Sauvignon Blanc",
    "White Blend",
    "Roter Veltliner",
}
bubbly = {
    "Champagne Blend",
    "Pinot Blanc",
    "Portuguese Sparkling",
    "Sparkling Blend",
    "Bical",
    "Glera",
    "Prosecco",
}

wine = pd.read_csv("/Users/brianwright/Downloads/wine-reviews/winemag-data-130k-v2.csv")
sia = SentimentIntensityAnalyzer()

wine["sentiment"] = wine["description"].apply(
    lambda x: sia.polarity_scores(x)["compound"]
)

wine['broad_category'] = wine['variety'].apply(lambda x: wine_assigner(x,reds,whites,bubbly))

wine.to_csv('wine_w_sentiment_and_metadata.csv')
